'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
<<<<<<< HEAD
'     Versión de runtime:4.0.30319.42000
=======
'     Versión de runtime:4.0.30319.34209
>>>>>>> 1b28ee0fce7a3094c154bf3eeec2639b0ee44b38
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTA: este archivo se genera de forma automática; no lo modifique directamente. Para realizar cambios,
    ' o si detecta errores de compilación en este archivo, vaya al Diseñador de proyectos
    ' (vaya a Propiedades del proyecto o haga doble clic en el nodo My Project en el
    ' Explorador de soluciones) y realice cambios en la ficha Aplicación.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
<<<<<<< HEAD
            Me.MainForm = Global.Proyecto_Biblioteca.Seleccion_Revistas
=======
            Me.MainForm = Global.Proyecto_Biblioteca.LOGIN
>>>>>>> 1b28ee0fce7a3094c154bf3eeec2639b0ee44b38
        End Sub
    End Class
End Namespace
